//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "curriculo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub nome: String,
    pub cpf: String,
    pub celular: String,
    pub id_setor: u32,
    pub data_entrevista: Option<DateTime>,
    pub contratado: bool,
    pub anexo: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub observação: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::setor::Entity",
        from = "Column::IdSetor",
        to = "super::setor::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Setor,
}

impl Related<super::setor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Setor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
