//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "setor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub nome: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::curriculo::Entity")]
    Curriculo,
}

impl Related<super::curriculo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Curriculo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
